version: "3.8"
services:
  db:
    image: postgres:13
    container_name: postgres_db
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: 1201
      POSTGRES_DB: contactos_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data #guarda los datos en el volumen data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U root"]
      interval: 5s
      timeout: 5s
      retries: 5
    restart: always
    shm_size: 128mb

  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: deymarbrian02@gmail.com
      PGADMIN_DEFAULT_PASSWORD: 12012005
    ports:
      - "8081:80" #entrar con edge
    depends_on:
      db:
        condition: service_healthy

volumes:
  postgres_data:
